[[redirects]]
  from = "/*"
  # to = "/index.html"
  to = "/.netlify/functions/site/index"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/.netlify/functions/site/index"
  status = 200
  force = true

[build]
  command = "npm run build"
  functions = "api"
  publish = "/api/site/dist"