[[redirects]]
  from = "/*"
  # to = "/index.html"
  to = "/.netlify/functions/site/index"
  status = 200

[build]
  command = "npm run build"
  functions = "api"
  publish = "/api/site/dist"